function mindiana(){var O='bootstrap',P='begin',Q='gwt.codesvr.mindiana=',R='gwt.codesvr=',S='mindiana',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='mindiana::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='mindiana.nocache.js',Ib='base',Jb='//',Kb='gwt.logging.firebugHandler',Lb='phonegap.env',Mb='android',Nb='ipad',Ob='ipod',Pb='iphone',Qb='blackberry',Rb='file://',Sb='yes',Tb='no',Ub='user.agent',Vb='webkit',Wb='safari',Xb='msie',Yb=10,Zb=11,$b='ie10',_b=9,ac='ie9',bc=8,cc='ie8',dc='gecko',ec='gecko1_8',fc=2,gc=3,hc=4,ic='selectingPermutation',jc='mindiana.devmode.js',kc='DISABLED',lc='314DF06053EF4D3C3090C8B3464C1309',mc='ENABLED',nc=':1',oc='335B9AD8CB89F5393893FC510C3AE308',pc='3952AD6C258D215F3047B0B592F416A9',qc='56522DA624BCF0FF31EFCD087515946E',rc='BECF4406F9F8FDEB2F626757111BBE35',sc='C841C3BA034B032A7FD98FFFCD91DF52',tc=':',uc='.cache.js',vc='link',wc='rel',xc='stylesheet',yc='href',zc='loadExternalRefs',Ac='gwt/clean/clean.css',Bc='end',Cc='http:',Dc='file:',Ec='_gwt_dummy_',Fc='__gwtDevModeHook:mindiana',Gc='Ignoring non-whitelisted Dev Mode URL: ',Hc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({'moduleName':S,'sessionId':o.__gwtStatsSessionId,'subSystem':T,'evtGroup':a,'millis':(new Date).getTime(),'type':b})}}
mindiana.__sendStats=r;mindiana.__moduleName=S;mindiana.__errFn=null;mindiana.__moduleBase=U;mindiana.__softPermutationId=V;mindiana.__computePropValue=null;mindiana.__getPropMap=null;mindiana.__installRunAsyncCode=function(){};mindiana.__gwtStartLoadingFragment=function(){return null};mindiana.__gwt_isKnownPropertyValue=function(){return false};mindiana.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={'moduleName':S};mindiana.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[mindiana.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
mindiana.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(mindiana.__errFn){n.onerror=function(){mindiana.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
mindiana.__startLoadingFragment=function(a){return D(a)};mindiana.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;mindiana.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return mindiana.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){return __gwt_getMetaProperty(Kb)};i[Kb]={'DISABLED':V,'ENABLED':W};j[Lb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Mb)!=-1||(a.indexOf(Nb)!=-1||(a.indexOf(Ob)!=-1||(a.indexOf(Pb)!=-1||a.indexOf(Qb)!=-1)))){var b=document.location.href;if(b.indexOf(Rb)===V){return Sb}}return Tb}};i[Lb]={'no':V,'yes':W};j[Ub]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Vb)!=-1}())return Wb;if(function(){return a.indexOf(Xb)!=-1&&(b>=Yb&&b<Zb)}())return $b;if(function(){return a.indexOf(Xb)!=-1&&(b>=_b&&b<Zb)}())return ac;if(function(){return a.indexOf(Xb)!=-1&&(b>=bc&&b<Zb)}())return cc;if(function(){return a.indexOf(dc)!=-1||b>=Zb}())return ec;return bb};i[Ub]={'gecko1_8':V,'ie10':W,'ie8':fc,'ie9':gc,'safari':hc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};mindiana.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};mindiana.__computePropValue=k;o.__gwt_activeModules[S].bindings=mindiana.__getPropMap;r(O,ic);if(q()){return D(jc)}var l;try{h([kc,Tb,ac],lc);h([mc,Tb,ac],lc);h([kc,Tb,ac],lc+nc);h([mc,Tb,ac],lc+nc);h([kc,Tb,Wb],oc);h([mc,Tb,Wb],oc);h([kc,Tb,Wb],oc+nc);h([mc,Tb,Wb],oc+nc);h([kc,Sb,Wb],pc);h([mc,Sb,Wb],pc);h([kc,Sb,Wb],pc+nc);h([mc,Sb,Wb],pc+nc);h([kc,Tb,cc],qc);h([mc,Tb,cc],qc);h([kc,Tb,cc],qc+nc);h([mc,Tb,cc],qc+nc);h([kc,Tb,$b],rc);h([mc,Tb,$b],rc);h([kc,Tb,$b],rc+nc);h([mc,Tb,$b],rc+nc);h([kc,Tb,ec],sc);h([mc,Tb,ec],sc);h([kc,Tb,ec],sc+nc);h([mc,Tb,ec],sc+nc);l=f[k(Kb)][k(Lb)][k(Ub)];var m=l.indexOf(tc);if(m!=-1){g=parseInt(l.substring(m+W),Yb);l=l.substring(V,m)}}catch(a){}mindiana.__softPermutationId=g;return D(l+uc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(vc);b.setAttribute(wc,xc);b.setAttribute(yc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(zc,P);c(Ac);r(zc,Bc)}
B();mindiana.__moduleBase=C();t[S].moduleBase=mindiana.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Cc||o.location.protocol==Dc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Ec;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Fc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Gc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Hc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Bc);A(H);return true}
mindiana.succeeded=mindiana();